defaults:
  deploy_cmd: gem push *.gem
  before_deploy_cmds:
    - op tag-release
    - sed -i '' -e "s/\".*/\"$(git tag | tail -1 | sed s/v//)\"/" lib/aws-security-czar/version.rb
    - git add  lib/aws-security-czar/version.rb
    - git commit -m "Version Bump" && git push
    - gem build aws-security-czar.gemspec
  after_deploy_cmds:
    - rm *.gem
environments:
  -
    rubygems: {}
